### ISSUE TITLE
package.json not being generated

### ISSUE THREAD

**Issue by alpyne** [north/generator-north#2]
At the end of the "yo north" run (choosing Gulp and server and watch task options), the following error occurs (I think) because no package.json file is generated.

```
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

Git: undefined
npm ERR! install Couldn't read dependencies
```

**Comment by Snugug** [comment]
What options did you run `yo north` with, if any? Do you have `git` installed and available globally? What about `bower` and `gulp`?

**Comment by alpyne** [comment]
yo north --init
git v1.8.4.1 installed and available
bower 1.3.2
gulp 3.6.0

**Comment by Snugug** [comment]
Okay, there's a known issue with --init at the moment and I haven't been able to track it down. In the meantime, I'd recommend running it w/o --init (it will create a new folder) and in that folder run the following (if you want Git):

```
git init
```

```
git remote add origin {github clone URL}
```

**Comment by alpyne** [comment]
Ok - that did it thanks. Just FYI, still getting the "git undefined" message as above. Cheers!

**Comment by Snugug** [comment]
Weird, I'll look into that.
